### ISSUE TITLE
Question about Binary digits?

### ISSUE THREAD

**Issue by jakevossen5** [julianthome/smtlibv2-grammar#4]
In the grammer, there is the folliwng rule

```
Binary:
    BinaryDigit+
    ;
```

However, according to the specification (page 22 of this pdf: http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf)

> A〈binary〉is a non-empty sequence of the characters 0 and 1 preceded by the characters #b.

This can be seen just below Binary with the HexDecimal rule. Is there a reason that this isn't here for binary, or am I missing something?

**Comment by julianthome** [comment]
@jakevossen5 awesome! Thank you very much for pointing this out. This is indeed a bug. Would you mind open a PR for this?
