### ISSUE TITLE
HexDecimal

### ISSUE THREAD

**Issue by roundEaredSengi** [julianthome/smtlibv2-grammar#6]
Hello, HexDecimal is currently derived to:

HexDecimal
    : '#x' HexDigit HexDigit HexDigit HexDigit
    ;

Shouldn't that be the following according to [http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf) :

HexDecimal
    : '#x' HexDigit+
    ;

I might also be misunderstanding sth. - in that case sorry :D

**Comment by julianthome** [comment]
Yes, that is true, the specification in this grammar does not adhere to the specs: 
> #x followed by a non-empty sequence of digits and letters
> from A to F , capitalized or not

Thanks for catching this issue. Preparing a PR to fix that 👍🏼

**Comment by julianthome** [comment]
Thanks a lot @roundEaredSengi for spotting this issue 👍🏼
